name: OWASP Juice Shop Security Testing

on:
  push:  # Trigger on push events

jobs:
  devskim-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create output directory
        run: mkdir -p output

      - name: Set up DevSkim
        uses: microsoft/devskim-action@v1
        with:
          directory-to-scan: routes
          should-scan-archives: false
          output-filename: devskim-results.sarif
          output-directory: output

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: devskim-results
          path: output/devskim-results.sarif

      - name: Use GitHub Token
        run: |
          echo "Using GitHub Token"
          echo "${{ secrets.GITHUB_TOKEN }}"
