# Friendly name for the workflow in GitHub
name: DevSkim Vulnerability Scan

# Run the workflow each time code is pushed or when a pull-request is created
on: [push, pull_request]

jobs:
  security-scan:
    name: DevSkim Security Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Create output directory for scan results if it doesn't exist
      - name: Create Output Directory
        run: mkdir -p .github/workflows/output

      # Run DevSkim for security vulnerability scanning
      - name: Run DevSkim Security Scan
        uses: microsoft/devskim-action@v1
        with:
          directory-to-scan: ./
          should-scan-archives: false
          output-filename: devskim-results.sarif
          output-directory: .github/workflows/output

      # Upload scan results as an artifact
      - name: Upload DevSkim Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: devskim-scan-results
          path: .github/workflows/output/devskim-results.sarif
